services:
  api:
    build:
      context: ./src
      dockerfile: Api/Dockerfile.dev
    volumes:
      - ./src:/src
      - api_artifacts:/src/artifacts
    environment:
      DOTNET_USE_POLLING_FILE_WATCHER: "true"

  worker:
    build:
      context: ./src
      dockerfile: Api/Dockerfile.dev
    volumes:
      - ./src:/src
      - worker_artifacts:/src/artifacts
    environment:
      DOTNET_USE_POLLING_FILE_WATCHER: "true"

volumes:
  api_artifacts:
  worker_artifacts:
