<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="FluentValidation" />
    <PackageReference Include="MediatR" />
    <!-- только атрибуты событий ([EntityName], [MessageUrn]), без транспорта -->
    <PackageReference Include="MassTransit.Abstractions" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Catalog.Domain\Catalog.Domain.csproj" />
    <ProjectReference Include="..\..\..\..\..\Shared\Core\Shared.Application\Shared.Application.csproj" />
  </ItemGroup>

</Project>
