<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="FluentValidation" />
    <PackageReference Include="MediatR" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Payment.Domain\Payment.Domain.csproj" />
    <ProjectReference Include="..\..\..\..\..\Shared\Core\Shared.Application\Shared.Application.csproj" />
  </ItemGroup>

</Project>
